[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
clearscreen = "3.0.0"
glam = "0.29.2"
itertools = "0.13.0"
nom = "7.1.3"
strum = "0.26.3"
strum_macros = "0.26.4"
vecgrid = "0.2.2"
